import json, re, os, traceback

import constants as _C
from utils.Config import Config
from utils.Tools import _warn, _info
from frameworks.Framework import Framework
from frameworks.helper.WATools import WATools


class WAFRBase(Framework):
    """
    Shared base class for all AWS Well-Architected Framework pillar frameworks
    (WAFS, WAFO, WARL, WAPE, WACO, WASU).

    Subclasses must set the class-level attribute:
        WA_PILLAR_ID (str): the pillarId string accepted by the WA Tool API,
            e.g. 'security', 'reliability', 'operationalExcellence',
            'performance', 'costOptimization', 'sustainability'.
    """

    # Subclasses override this
    WA_PILLAR_ID: str = 'security'

    WATools = None
    ResultCache = {}
    isBeta = False

    def __init__(self, data):
        super().__init__(data)
        self.isBeta = Config.get('beta', False)

        # Filename of the latest Well-Architected Framework Review report PDF
        # written by ``_hookPostBuildContentDetail``. Lives on the framework
        # instance (rather than global Config) so the PageBuilder can read it
        # directly without temporal coupling and so cross-account runs each
        # carry their own value.
        self.reportFilename = None

        self.WATools = None
        waTools = WATools(self.WA_PILLAR_ID)
        cliParams = Config.get('_SS_PARAMS')

        self.ResultCache = {}
        tmpParams = {}
        if 'others' in cliParams and cliParams['others'] is not None:
            params = cliParams['others']
            cfg = json.loads(params)
            if 'WA' in cfg:
                tmpParams = cfg['WA']

        if waTools.preCheck(tmpParams):
            self.WATools = waTools
            self.WATools.init(tmpParams)
            self.WATools.createReportIfNotExists()
            self.WATools.listAnswers()

    # ------------------------------------------------------------------
    # Hooks called by Framework.generateMappingInformation()
    # ------------------------------------------------------------------

    def _hookPostItemActivity(self, title, section, checks, comp):
        if self.WATools is None or self.WATools.HASPERMISSION is False:
            return title, section, checks, comp

        titleNum = self.extractNumber(title)
        sectNum  = self.extractNumber(section)
        paired   = "{}::{}".format(titleNum, sectNum)

        newChecks = "<h4>{}</h4>{}".format(
            self.getDescription(titleNum, paired), checks
        )

        titleKey = self.WATools.answerSets.get(titleNum, [None])[0]
        if titleKey not in self.ResultCache:
            self.ResultCache[titleKey] = {"0": [], "1": [], "-1": []}

        if titleKey is not None:
            if comp == 1:
                choice = self.WATools.answerSets.get(paired, [None])[0]
                if choice and choice not in self.ResultCache[titleKey]["1"]:
                    self.ResultCache[titleKey]["1"].append(choice)
            elif comp == -1:
                choice = self.WATools.answerSets.get(paired, [None, None])[1]
                if choice and choice not in self.ResultCache[titleKey]["-1"]:
                    self.ResultCache[titleKey]["-1"].append(choice)
            else:
                choice = self.WATools.answerSets.get(paired, [None])[0]
                if choice and choice not in self.ResultCache[titleKey]["0"]:
                    self.ResultCache[titleKey]["0"].append(choice)

        return title, section, newChecks, comp

    def _hookPostItemsLoop(self):
        if self.WATools is None or self.WATools.HASPERMISSION is False:
            return

        for title, opts in self.ResultCache.items():
            if len(opts["1"]) == 0 and len(opts["-1"]) == 0:
                continue

            if title is None or title == '':
                _warn(f"[{self.__class__.__name__}]: Skipping invalid title/questionId: {title}")
                continue

            # Clean selectedChoices
            ansStr = opts["1"]
            if isinstance(ansStr, list):
                ansStr = [c for c in ansStr if c is not None and c != '']
                ansStr = list(dict.fromkeys(ansStr))
            elif ansStr is None:
                ansStr = []

            # Build unselected notes from failed items
            failed_items = opts["-1"]
            if isinstance(failed_items, list):
                failed_items = [i for i in failed_items if i is not None and i != '']
                failed_items = list(dict.fromkeys(failed_items))

            if failed_items:
                unselectedNotes = (
                    "***Generated by SS\n\n"
                    "Here are the items failed SS checks (if any):\n- "
                    + "\n- ".join(failed_items)
                )
            else:
                unselectedNotes = "***Generated by SS\n\nNo failed items found."

            if title and (ansStr or unselectedNotes):
                try:
                    self.WATools.updateAnswers(title, ansStr, unselectedNotes)
                except Exception as e:
                    _warn(f"[{self.__class__.__name__}]: Error updating answers for {title}: {str(e)}")
            else:
                _warn(f"[{self.__class__.__name__}]: Skipping update for {title} - insufficient data")

    def _hookPostBuildContentDetail(self):
        if self.WATools is None or self.WATools.HASPERMISSION is False:
            return

        self.WATools.createMilestoneIfNotExists()

        # Generate Well-Architected Framework Review Report (PDF) and save it:
        # 1) Inside the account HTML folder so the page download button works
        # 2) Inside usecases/wa-summarizer/wafr_report for downstream tooling
        try:
            acctFolder  = Config.get('HTML_ACCOUNT_FOLDER_FULLPATH')
            wafrLocalDir = os.path.join(
                _C.ROOT_DIR, 'usecases', 'wa-summarizer', 'wafr_report'
            )

            output_dirs = []
            if acctFolder:
                output_dirs.append(acctFolder)
            output_dirs.append(wafrLocalDir)

            written = self.WATools.generateReviewReport(output_dirs=output_dirs)
            if written:
                self.reportFilename = self.WATools.waInfo.get('LatestReportFilename')

        except (OSError, IOError) as e:
            _warn(f"[{self.__class__.__name__}]: Filesystem error while saving review report: {str(e)}")
            _warn(traceback.format_exc())
        except Exception as e:
            _warn(f"[{self.__class__.__name__}]: Unable to generate review report: {str(e)}")
            _warn(traceback.format_exc())

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def extractNumber(self, s):
        match = re.search(r'\d+', s)
        return match.group() if match else None

    def getDescription(self, titleNum, paired):
        titleStr = self.WATools.answerSets.get(titleNum, [None])[1]
        sectStr  = self.WATools.answerSets.get(paired,    [None])[1]
        return f"{titleStr} - {sectStr}"
