import json, re, os, traceback

import constants as _C
from utils.Config import Config
from utils.Tools import _warn, _info
from frameworks.Framework import Framework
from frameworks.helper.WATools import WATools

class WAFS(Framework):
    WATools = None
    ResultCache = {}
    isBeta = False
    def __init__(self, data):
        super().__init__(data)
        self.isBeta = Config.get('beta', False)

        # Filename of the latest Well-Architected Framework Review report PDF
        # written by ``_hookPostBuildContentDetail``. Lives on the framework
        # instance (rather than global Config) so the WAFSPageBuilder can read
        # it directly without temporal coupling and so cross-account runs each
        # carry their own value.
        self.reportFilename = None

        self.WATools = None
        waTools = WATools('security')
        cliParams = Config.get('_SS_PARAMS')

        tmpParams = {}
        self.ResultCache = {}
        if 'others' in cliParams and not cliParams['others'] == None:
            params = cliParams['others']
            cfg = json.loads(params)

            if 'WA' in cfg:
                tmpParams = cfg['WA']

        if waTools.preCheck(tmpParams): 
            self.WATools = waTools
            self.WATools.init(tmpParams)
            self.WATools.createReportIfNotExists()
            self.WATools.listAnswers()
            # print(self.WATools.answerSets)
        

    def _hookPostItemActivity(self, title, section, checks, comp):
        if self.WATools == None or self.WATools.HASPERMISSION == False:
            return title, section, checks, comp
        
        titleNum = self.extractNumber(title)
        sectNum = self.extractNumber(section)

        paired = "{}::{}".format(titleNum, sectNum)

        newChecks = "<h4>{}</h4>{}".format(self.getDescription(titleNum, paired), checks) 

        titleKey = self.WATools.answerSets.get(titleNum, [None])[0] if isinstance(self.WATools.answerSets.get(titleNum), list) else None
        if not titleKey in self.ResultCache:
            self.ResultCache[titleKey] = {
                "0": [],
                "1": [],
                "-1": []
            }

        if not titleKey == None:
            entry = self.WATools.answerSets.get(paired)
            if not isinstance(entry, list):
                entry = [None, None]
            elif len(entry) < 2:
                entry = list(entry) + [None] * (2 - len(entry))
            if comp == 1:
                choice = entry[0]
                if choice and choice not in self.ResultCache[titleKey]["1"]:
                    self.ResultCache[titleKey]["1"].append(choice)
            elif comp == -1:
                choice = entry[1]
                if choice and choice not in self.ResultCache[titleKey]["-1"]:
                    self.ResultCache[titleKey]["-1"].append(choice)
            else:
                choice = entry[0]
                if choice and choice not in self.ResultCache[titleKey]["0"]:
                    self.ResultCache[titleKey]["0"].append(choice)

        return title, section, newChecks, comp
        
    def _hookPostItemsLoop(self):
        if self.WATools == None or self.WATools.HASPERMISSION == False:
            return

        for title, opts in self.ResultCache.items():
            if len(opts["1"]) == 0 and len(opts["-1"]) == 0:
                continue 

            # Validate title (questionId)
            if title is None or title == '':
                _warn(f"[WAFS]: Skipping invalid title/questionId: {title}")
                continue

            # Clean and validate selectedChoices
            ansStr = opts["1"]
            if isinstance(ansStr, list):
                # Filter out None and empty values, then remove duplicates
                ansStr = [choice for choice in ansStr if choice is not None and choice != '']
                ansStr = list(dict.fromkeys(ansStr))  # Remove duplicates while preserving order
            elif ansStr is None:
                ansStr = []
            
            # Validate unselectedNotes
            failed_items = opts["-1"]
            if isinstance(failed_items, list):
                # Filter out None and empty values, then remove duplicates
                failed_items = [item for item in failed_items if item is not None and item != '']
                failed_items = list(dict.fromkeys(failed_items))  # Remove duplicates
            
            if failed_items:
                unselectedNotes = "***Generated by SS\n\nHere are the items failed SS checks (if any):\n- {}".format("\n- ".join(failed_items))
            else:
                unselectedNotes = "***Generated by SS\n\nNo failed items found."

            # Only call updateAnswers if we have valid data
            if title and (ansStr or unselectedNotes):
                try:
                    self.WATools.updateAnswers(title, ansStr, unselectedNotes)
                except Exception as e:
                    _warn(f"[WAFS]: Error updating answers for {title}: {str(e)}")
            else:
                _warn(f"[WAFS]: Skipping update for {title} - insufficient data")

        pass

    def extractNumber(self, s):
        match = re.search(r'\d+', s)
        return match.group() if match else None
    
    def getDescription(self, titleNum, paired):
        # Safe lookup — REL09/REL13 keys added to the WAFS map are not part
        # of the Security-pillar WA Tool answerSets, so the lookup may return
        # [None] (a length-1 list) or None. Fall back to the raw identifier.
        titleEntry = self.WATools.answerSets.get(titleNum)
        if isinstance(titleEntry, list) and len(titleEntry) >= 2:
            titleStr = titleEntry[1]
        else:
            titleStr = titleNum
        sectEntry = self.WATools.answerSets.get(paired)
        if isinstance(sectEntry, list) and len(sectEntry) >= 2:
            sectStr = sectEntry[1]
        else:
            sectStr = paired
        return f"{titleStr} - {sectStr}"

    def _hookPostBuildContentDetail(self):
        if self.WATools is None or self.WATools.HASPERMISSION is False:
            return

        self.WATools.createMilestoneIfNotExists()

        # Generate Well-Architected Framework Review Report (PDF) and save it
        # 1) Inside the WAFS account folder so the WAFS.html download button works
        # 2) Inside usecases/wa-summarizer/wafr_report for downstream summarizer tooling
        try:
            acctFolder = Config.get('HTML_ACCOUNT_FOLDER_FULLPATH')
            wafrLocalDir = os.path.join(_C.ROOT_DIR, 'usecases', 'wa-summarizer', 'wafr_report')

            output_dirs = []
            if acctFolder:
                output_dirs.append(acctFolder)
            output_dirs.append(wafrLocalDir)

            written = self.WATools.generateReviewReport(output_dirs=output_dirs)
            if written:
                # Expose the filename via the framework instance so WAFSPageBuilder
                # can pick it up explicitly through ``self.framework.reportFilename``
                # rather than via global Config.
                self.reportFilename = self.WATools.waInfo.get('LatestReportFilename')
        except (OSError, IOError) as e:
            # Filesystem failures while writing the PDF copies — surface details
            # so operators can fix permissions/disk-space issues.
            _warn(f"[WAFS]: Filesystem error while saving review report: {str(e)}")
            _warn(traceback.format_exc())
        except Exception as e:
            # Anything else is unexpected. Don't fail the whole framework run,
            # but log a full traceback so the failure is diagnosable instead of
            # being silently dropped.
            _warn(f"[WAFS]: Unable to generate review report: {str(e)}")
            _warn(traceback.format_exc())
